baseURL = "https://dehongblog1.netlify.com/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
title = " DeHong.Website "
theme = "hugo-nuo" 
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$","_cache$"]
enableEmoji = true

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
# googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "©Blog|德宏 All rights reserved. "

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "博客"
  weight = 20
  identifier = "works"
  url = "https://dehong.rbind.io/"

# Add your own params here
[params]
  author = "德宏"
  avatar = "/img/avatar.jpg" 
  seotitle = "Blog|德宏"
  subtitle = "~ 带着爱和梦想生活 ~"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "1126714486@qq.com"
  github = "Dehong1"
   #twitter = "/"
   #linkedin = "/"
  weibo = "/"
  wechat= "/img/qrcode.jpg/" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
    changyan = true
    changyanId = "cytkoYA6X"
    changyanConf = "81c732dc10bd6e29b8f4208b6377e150"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
    baiduTongji = "19fbec944977a82f7082273dd3e41091"

  # ICP Number (China Only)
  # ICP = "鲁ICP备16005986号-2"
