---
title: 学R第三天
author: 德宏
date: '2017-12-08'
slug: 学r第三天
isCJKLanguage: 
categories:
  - R
tags:
  - ggplot
---


* 参考《30分钟学会ggplot2》肖凯，基本概念

<!--more-->


<!-- toc -->

#### 1. 用mpg生成散点图
```{r}


library("ggplot2") #载入ggplot2;
str(mpg) #查看mpg数据集的变量类型
p<-ggplot(mpg,mapping=aes(x=cty,y=hwy)) #以mpg为数据集，将变量cty(在城市中每加仑油跑的距离)，hwy(高速公路)mapping(映射)到x.y（aesthetics）轴上。
p+geom_point() #在图上加上几何对象：点（geometric piont）
p ;p+geom_point()#展示
summary(p);summary(p+geom_point()) #查看对象的摘要描述

```
#### 2.将年份映射到颜色属性上
```{r}
p<-ggplot(mpg,mapping = aes(x = cty,y = hwy,colour = factor(year)))
p+geom_point()
```
#### 3.添加平滑曲线
```{r}
p+geom_point()+stat_smooth()
rm(p) #清楚变量p，将年份只映射到点的颜色属性上P pP
p <- ggplot(mpg, aes(x=cty,y=hwy))
p + geom_point(aes(colour=factor(year)))+stat_smooth()
```
#### 4.换种思路绘一遍
```{r}
d <- ggplot() +
geom_point(data=mpg, aes(x=cty, y=hwy, colour=factor(year)))+
stat_smooth(data=mpg, aes(x=cty, y=hwy))
#必须明确data eg no:d<-ggplot()+geom_point(mpg,aes(x=cty,y=hwy,colour=factor(year)))+stat_smooth(mpg,aes(x=cty,y=hwy))
# 原因：ggplot与geom_各自的data与mapping的位置不一致，eg yes:d<-ggplot()+geom_point(aes(x=cty,y=hwy,colour=factor(year)),mpg)+stat_smooth(aes(x=cty,y=hwy),mpg)
print(d)#此时除了底层画布外，有两个图层，分别定义了geom和 stat。
```
#### 5.用标度（scale)来修改颜色取值

scale_color_manual说明：This allows you to specify you own set of mappings from levels in the data to aesthetic values.
```{r}
d+scale_color_manual(values = c("yellow","red"))
```
#### 6.将排量映射到散点的大小上
```{r}
d <- ggplot() +
geom_point(data=mpg, aes(x=cty, y=hwy, colour=factor(year),size=displ),alpha=0.5,position = "jitter")+
stat_smooth(data=mpg, aes(x=cty, y=hwy))
d+scale_color_manual(values = c("yellow","red"))+coord_cartesian(xlim = c(15, 25),ylim=c(15,40)) #用坐标控制图形显示的范围
```
#### 7.用facet（分面）显示不同年份的数据
```{r}
d <- ggplot() +
geom_point(data=mpg, aes(x=cty, y=hwy, colour=factor(year),size=displ),alpha=0.5,position = "jitter")+
stat_smooth(data=mpg, aes(x=cty, y=hwy))
d+scale_color_manual(values = c("yellow","red"))+coord_cartesian(xlim = c(15, 25),ylim=c(15,40))+facet_wrap(~year,nrow=2)
```
#### 6.增加图名幵精细修改图例
```{r}
d <- ggplot() +
geom_point(data=mpg, aes(x=cty, y=hwy, colour=factor(year),size=displ),alpha=0.5,position = "jitter")+
stat_smooth(data=mpg, aes(x=cty, y=hwy))
d+scale_color_manual(values = c("yellow","red"))+coord_cartesian(xlim = c(15, 25),ylim=c(15,40))+facet_wrap(~year,nrow=2)+
labs(y='每加仑高速公路行驶距离',x='每加仑城市公路行驶距离')+guides(size=guide_legend(title='排量'),colour = guide_legend(title='车型',override.aes=list(size=5)))+ggtitle('汽车油耗与型号')#不知道怎么居中
```

### 今天先到这儿，ggplot2似乎有些博大精深………………




